apiVersion: batch/v1
kind: Job
metadata:
  name: krp-curl-verb-override
spec:
  template:
    metadata:
      name: krp-curl-verb-override
    spec:
      containers:
      - name: krp-curl
        image: quay.io/brancz/krp-curl:v0.0.2
        env:
        - name: SERVICE_URL
          value: "https://kube-rbac-proxy-verb-override.default.svc:8443"
      restartPolicy: Never
  backoffLimit: 4